export const CLASSROOM_TYPES = {
  CREATE_CLASSROOM: 'CREATE_CLASSROOM',
  LOADING_CLASSROOM: 'LOADING_CLASSROOM',
  GET_CLASSROOMS: 'GET_CLASSROOMS',
  UPDATE_CLASSROOM: 'UPDATE_CLASSROOM',
  GET_CLASSROOM: 'GET_CLASSROOM',
  DELETE_CLASSROOM: 'DELETE_CLASSROOM',
};
