export const EXERCISE_TYPES = {
  CREATE_EXERCISE: 'CREATE_EXERCISE',
  LOADING_EXERCISE: 'LOADING_EXERCISE',
  GET_EXERCISES: 'GET_EXERCISES',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  GET_EXERCISE: 'GET_EXERCISE',
  DELETE_EXERCISE: 'DELETE_EXERCISE',
};
