export const FORUM_TYPES = {
  CREATE_FORUM: 'CREATE_FORUM',
  LOADING_FORUM: 'LOADING_FORUM',
  GET_FORUMS: 'GET_FORUMS',
  UPDATE_FORUM: 'UPDATE_FORUM',
  GET_FORUM: 'GET_FORUM',
  DELETE_FORUM: 'DELETE_FORUM',
};
